version: '3.4'

services:
  nodejs:
    build:
      context: .
    container_name: nodevuejs
    working_dir: /srv/app
    environment:
      - NODE_ENV=dev
      - USE_DOCKER_BIN=false
    volumes:
      - ..:/srv/app:rw,cached
    expose:
      - "8081"
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8081:8080"
